version: 0.2

phases:
  install:
    commands:
      # Install Node 22
      - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
      - node -v
      - npm -v

      # Install dependencies
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist